### PR TITLE
REDO: MySQL getBan - single querry instead of querry whole table

### PR DESCRIPTION
**Pull request by mickare**
REDO of a messed pull request of a messed up maven project.

Instead of getting the whole table of banned players, when trying to get a ban, just get the single BanEntry for the player & server.

This keeps the traffic and the work time on the database low.

### CODE REVIEW

**Comment by roblabla** [comment]
Bleh. I think it is because of the line endings. You on windows or Linux/Mac ?

**Comment by mickare** [comment]
Windows

**Comment by roblabla** [comment]
Yeah ok, so what happened is your git is configured to normalize line ending to unix-style line endings. What I'm going to do (if you're fine with it) is pull your changes and merge them manually. I'll give credit where credit is due, of course.

**Comment by mickare** [comment]
okay ^^

**Comment by roblabla** [comment]
Done. thank you for this ^^.

**Comment by mickare** [comment]
One question: So you have the new line delimiter with "Windows"? Then I'll adopt...

**Comment by mickare** [comment]
$ git config --global core.autocrlf true

**Pull request closed without merging**
